### Cadastrar um novo item de venda
POST https://localhost:5001/api/item/create
Content-Type: application/json

{
    "ProdutoId" : 2,
    "Quantidade" : 1,
    "Preco" : 3.5,
    "CarrinhoId" : "931fdea3-55e2-4f88-abf0-f33c1a76c4c8"
}

### Listar todas as categorias
GET https://localhost:5001/api/item/getbycartid/931fdea3-55e2-4f88-abf0-f33c1a76c4c8